[package]
name = "xtask"
version = "0.15.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
bindgen = "0.63.0"
log = "0.4.6"
tempdir = "0.3.7"
