name: Release to crates.io

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-rbspy:
    name: Publish rbspy crate
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@984d158d699777abbaa79de23de3134e60c187fa # stable branch
      - name: publish rbspy crate
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
