name: Release to crates.io

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-ruby-structs:
    name: Publish rbspy-ruby-structs crate
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@984d158d699777abbaa79de23de3134e60c187fa # stable branch
      - name: publish ruby-structs crate
        continue-on-error: true
        run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cd ruby-structs
          cargo publish
